### ISSUE TITLE
The bot is not responding as it probably should.

### ISSUE THREAD

**Issue by Aftab-Shaikh-op** [FuseFairy/DiscordBot-BardGPT#10]
Hey there again FuseFairy! I've got a little problem here, 

When I asked the Bot "tell me little bit about yourself, give me a good introduction." by using the "/bard" command, The bot responded: 
"I'm designed solely to process and generate text, so I'm unable to assist you with that."

which is not the response bard gives.

when directly asked from https://bard.google.com it gives a proper introduction.

so, what are your thoughts on this?

**Comment by Aftab-Shaikh-op** [comment]
Also bro is taking a shit ton of time to think fr
![image](https://github.com/FuseFairy/DiscordBot-BardGPT/assets/98048206/ca06d775-55fc-424a-9d88-b8aba821e9cf)

**Comment by Aftab-Shaikh-op** [comment]
Lmao it's been more than half an hour now and it still hasn't responded

![image](https://github.com/FuseFairy/DiscordBot-BardGPT/assets/98048206/78c678ab-5e97-4a45-90e6-a8cab39bc48d)

**Comment by FuseFairy** [comment]
There are some issues with the bard api I'm using and I'm waiting for an update.

**Comment by FuseFairy** [comment]
I will update BardGPT as soon as possible after the bard api is updated.

**Comment by Aftab-Shaikh-op** [comment]
alright blud

**Comment by Aftab-Shaikh-op** [comment]
Hey blud, wassup? It's been a week

**Comment by Aftab-Shaikh-op** [comment]
just tell me yes or no if it's fixed or not. I don't want ignorance

**Comment by FuseFairy** [comment]
not yet

**Comment by Aftab-Shaikh-op** [comment]
I see, when do you think this issue would be resolved?

**Comment by FuseFairy** [comment]
not sure, I will update another repo first

**Comment by FuseFairy** [comment]
update finish
