### ISSUE TITLE
little problem

### ISSUE THREAD

**Issue by coyottetv** [FuseFairy/DiscordBot-BardGPT#11]
hello when I make an @ bot name with an image and the text the bot responds to me ERROR: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.description: This field is required console error Traceback (most recent call last):
  File "/home/DiscordBot-BardGPT/src/response.py", line 84, in send_message
    await interaction.channel.send(text, embeds=images_embed)
  File "/usr/local/lib/python3.10/dist-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.description: This field is required

**Comment by Freenoob7878** [comment]
In response.py file at line 61 replace this:
`images_embed.append(discord.Embed(url=f"https://bard.google.com/{i}").set_image(url=image_link))`
With this
`images_embed.append(discord.Embed(description="Images", url=f"https://bard.google.com/{i}").set_image(url=image_link))`

**Comment by coyottetv** [comment]
thank you it works
