### ISSUE TITLE
The bot is not responding

### ISSUE THREAD

**Issue by occultwave** [FuseFairy/DiscordBot-BardGPT#5]
Hi! I'm trying to launch a bot. I installed discord bot token in .env file, then set a cookie in discord, but after trying to enter a command, the bot does not respond. (The request is not displayed in the bot log yet)
`[2023-06-12 18:06:06] [INFO    ] discord.client: logging in using static token
[2023-06-12 18:06:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f91e75371324b756a81a89a385c4cf50).
←[30;1m2023-06-12 18:06:09←[0m ←[34;1mINFO    ←[0m ←[35m__main__←[0m -> xxxx is now running!
Bot is Up and Ready!
Synced 3 commands
←[30;1m2023-06-12 18:06:35←[0m ←[33;1mWARNING ←[0m ←[35msrc.setChatbot←[0m -> ←[31user#xxxx set Google Bard successful←[0m
[2023-06-12 18:07:30] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session f91e75371324b756a81a89a385c4cf50.
[2023-06-12 18:08:14] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "load" is not found
[2023-06-12 18:08:27] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "unload" is not found`

**Comment by FuseFairy** [comment]
Did you use the !load and !unload commands to get this error?

**Comment by occultwave** [comment]
> Did you use the !load and !unload commands to get this error?
commands !load and !unload do not work

**Comment by FuseFairy** [comment]
command has been changed， please review the README.MD again

**Comment by occultwave** [comment]
> command has been changed, please review the README.md again

ok, bardgpt is already loaded, im tryin to start bot. i set up cookies via /bard_cookies and after that the bot does not respond to my requests via the /bard command

**Comment by FuseFairy** [comment]
I need error information

**Comment by occultwave** [comment]
> I need error information

there is no error here, just this
![Снимок экрана 2023-06-13 014449](https://github.com/FuseFairy/DiscordBot-BardGPT/assets/44018894/8e2580e1-52fb-4421-826d-b6a76cf17219)

**Comment by FuseFairy** [comment]
There is a chance of failure when using /bard for the first time

**Comment by FuseFairy** [comment]
I'll fix it later

**Comment by occultwave** [comment]
> I'll fix it later

ok, glad to hear that

**Comment by FuseFairy** [comment]
> > I'll fix it later
> 
> ok, glad to hear that

Sorry for the long wait, I think I fixed the problem.

**Comment by occultwave** [comment]
> > > I'll fix it later
> > 
> > 
> > ok, glad to hear that
> 
> Sorry for the long wait, I think I fixed the problem.

after the update i have the same problem (the bot generates the answer to the question for more than 10 minutes without answering)

**Comment by FuseFairy** [comment]
so strange, copy and past new code at src/response.py file, then run again
```
import discord
import asyncio
import re
from Bard import Chatbot
from src import log

logger = log.setup_logger(__name__)
using_func = {}

async def get_using_send(user_id):
    return using_func[user_id]

async def set_using_send(user_id, status: bool):
    using_func[user_id] = status

async def chatbot_ask(chatbot: Chatbot, message: str):
    loop = asyncio.get_running_loop()
    result = await loop.run_in_executor(None, chatbot.ask, message)
    return result

async def send_message(chatbot: Chatbot, interaction: discord.Interaction, user_message: str):
    using_func[interaction.user.id] = True
    reply = ''
    text = ''
    images_embed = []
    await interaction.response.defer(ephemeral=False, thinking=True)
    try:
        reply = await chatbot_ask(chatbot, user_message)
        print(f"reply: {reply}")
        # Get reply text
        text = f"{reply['content']}"
        text = re.sub(r'\[Image of[^\]]*?\].*?\n?', '', text)

        # Set the final message
        user_message = user_message.replace("\n", "")
        ask = f"> **{user_message}** - <@{str(interaction.user.id)}>\n\n"
        response = f"{ask}{text}"

        # Discord limit about 2000 characters for a message
        while len(response) > 2000:
            temp = response[:2000]
            response = response[2000:]
            await interaction.followup.send(temp)

        # Get the image, if available
        try:
            if reply["images"] != "set()":
                i = 1
                count = 0
                for image_link in reply["images"]:
                    if len(images_embed) < 10:
                        images_embed.append(discord.Embed(url=f"https://bard.google.com/{i}").set_image(url=image_link))
                        count += 1
                        if count == 4:
                            i += 1
                            count = 0
                    else:
                        break
        except:
            pass
        else:
            if images_embed:
                print(f"images_embed: {images_embed}")
                await interaction.followup.send(response, embeds=images_embed, wait=True)
            else:
                print("no images_embed")
                await interaction.followup.send(response, wait=True)
    except Exception as e:
            await interaction.followup.send(f">>> **Error while sending message: {e}**")
            logger.exception(f"Error while sending message: {e}")
    finally:
        using_func[interaction.user.id] = False
```

**Comment by occultwave** [comment]
> 

`←[30;1m2023-06-24 14:32:12←[0m ←[34;1mINFO    ←[0m ←[35mcogs.bardgpt←[0m -> ←[31mxxxxxx#0←[0m : 'how to improve my physical health' (bard-gpt)
reply: {'content': 'Google Bard encountered an error: b\')]}\\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n57\\n[["di",118],["af.httprm",117,"4467953137932039315",29]]\\n25\\n[["e",4,null,null,132]]\\n\'.'}`

**Comment by FuseFairy** [comment]
well, look like bard problem

**Comment by occultwave** [comment]
> well, look like bard problem

should i change the cookies?

**Comment by FuseFairy** [comment]
I'm not sure, here has same issue
https://github.com/acheong08/Bard/issues/41

**Comment by FuseFairy** [comment]
maybe you should change ip address.

**Comment by occultwave** [comment]
> maybe you should change ip address.


You turned out to be right. In order for the bot to answer, I have to turn on vpn. How difficult will it be for you to add proxy support to the bot?

**Comment by FuseFairy** [comment]
well, I'm think is difficult for me, maybe you can host your bot in another country.

**Comment by occultwave** [comment]
> well, I'm think is difficult for me, maybe you can host your bot in another country.


ok, I think hosting a bot in another country is a great solution
