### ISSUE TITLE
!upload error 

### ISSUE THREAD

**Issue by Murat1Na** [FuseFairy/DiscordBot-BardGPT#6]
2023-06-23 21:59:02 ERROR    discord.ext.commands.bot Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "upload" is not found

**Comment by FuseFairy** [comment]
https://github.com/FuseFairy/DiscordBot-BardGPT/issues/5#issuecomment-1587724549

**Comment by Murat1Ahmet** [comment]
> Prefix commands have been change. Please use !bardupload.
> 
> [#5 (comment)](https://github.com/FuseFairy/DiscordBot-BardGPT/issues/5#issuecomment-1587724549)

yes that worked but the bot doesn't reply, it keep thinking without response

**Comment by Murat1Ahmet** [comment]
when i used it as local host i got these errrors.

Error: 'NoneType' object is not subscriptable   
Error while sending message: 'NoneType' object is not subscriptable

**Comment by FuseFairy** [comment]
https://github.com/acheong08/Bard/issues/59

this is  api error, we can only wait for the api to be fixed.

**Comment by Murat1Ahmet** [comment]
> [acheong08/Bard#59](https://github.com/acheong08/Bard/issues/59)
> 
> this is api error, we can only wait for the api to be fixed.

no news about that?

**Comment by FuseFairy** [comment]
yes

**Comment by FuseFairy** [comment]
> > [acheong08/Bard#59](https://github.com/acheong08/Bard/issues/59)
> > this is api error, we can only wait for the api to be fixed.
> 
> no news about that?

I'm change another bard api, chatbot is working again.
