### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Murat1Na** [FuseFairy/DiscordBot-BardGPT#8]
Is there a way to make everyone use my own cookies since bard cookie take many messages until it expire then it work alone the next day, is there a way to make everyone use /chat and image without putting cookies just from my cookie in the code

**Comment by Murat1Na** [comment]
ig /chat and all comands will be more stayatble than @mention or reply

**Comment by FuseFairy** [comment]
If someone else is using `/bard` for the first time and their cookie has not been set before, your own cookie will be used

**Comment by FuseFairy** [comment]
So you want everyone to use their cookies and not yours?

**Comment by FuseFairy** [comment]
> ig /chat and all comands will be more stayatble than @mention or reply

if you don't want to use @mention, can delete cogs/event.py or use prefix command `!bardunload event`

**Comment by okura9** [comment]
Can I get everyone to use my cookies instead?

**Comment by FuseFairy** [comment]
> Can I get everyone to use my cookies instead?

yes, just choose set option

![image](https://github.com/FuseFairy/DiscordBot-BardGPT/assets/78064680/78ef7b83-a9c3-4fdf-a7a4-7e2b00e4acc8)
